### 
POST http://localhost:3333/categories
Content-Type: application/json

{
    "name": "Pablo Henrique",
    "description": "Receba, passou aqui!"
}

###
GET http://localhost:3333/categories
Content-Type: application/json

### 
POST http://localhost:3333/specifications
Content-Type: application/json

{
    "name": "Pablo Henrique",
    "description": "Etâ Porrá!"
}

###
POST http://localhost:333/categories/import
Content-Type: multipart/form-data
@file=file; filename="../"
